---
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    user: root
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    volumes:
      - /root/chrome-vps/config:/config
    ports:
      - 3010:3000
      - 3011:3001
    shm_size: "1gb"
    restart: unless-stopped
